apiVersion: v1
kind: Service
metadata:
  name: my-country-service
spec:
  type: NodePort
  selector:
    app: country-service
  ports:
    - port: 8086          # Port du service dans le cluster
      targetPort: 8086    # Port du container (Spring Boot)
      nodePort: 30081     # Port expos√© en externe
      protocol: TCP
